"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gzy9dxg(x==)q2)-&2n4m^)0wlf1e)a(+clg0l@^d)%yrz)e4&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['chadrackmbu.pythonanywhere.com']


# Application definition

INSTALLED_APPS = [
    #'grappelli',
    # 'admin_interface',
    # 'colorfield',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'portfolioapp',
    'django_ckeditor_5',
    'django.contrib.humanize',
    'django.contrib.sites',  # Nécessaire pour django-allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # Optionnel pour les connexions sociales
    'django_countries',

    'material',
    'material.admin',
    'csp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',  # Middleware pour django-allauth
]

# Configuration de django-allauth
SITE_ID = 1  # Identifiant du site (généralement 1 pour un seul site)

AUTHENTICATION_BACKENDS = [
    # Nécessaire pour django-allauth
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Redirections après connexion/déconnexion
LOGIN_REDIRECT_URL = 'home'  # Page de redirection après la connexion
#ACCOUNT_LOGOUT_REDIRECT_URL = 'home'  # Page de redirection après la déconnexion
# settings.py
LOGOUT_REDIRECT_URL = 'home'  # Remplacez 'home' par le nom de l'URL de votre page d'accueil

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'portfolioapp.context_processors.unread_notifications_count',  # Ajoutez cette ligne
                'portfolioapp.context_processors.global_context',  # Context processor global
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Kinshasa'

USE_I18N = True

USE_TZ = True

LANGUAGES = [
    ('fr', 'French'),
    ('en', 'English'),
]
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

# Configuration des fichiers statiques
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Pour le développement - Django cherche les fichiers ici
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Pour la production - collectstatic copie les fichiers ici
STATIC_ROOT = BASE_DIR / 'staticfiles'


# settings.py
LOGIN_URL = 'login'  # Nom de l'URL de connexion
#LOGIN_REDIRECT_URL = 'home'  # Page de redirection après la connexion
#LOGOUT_REDIRECT_URL = 'home'  # Page de redirection après la déconnexion
# Configuration de CKEditor 4
"""CKEDITOR_UPLOAD_PATH = "uploads/"  # Optionnel : pour permettre le téléversement de fichiers
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',  # Personnalisez la barre d'outils
        'height': 300,
        'width': '100%',
    },
}"""

# Custom color palette for CKEditor 5
customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

# CKEditor 5 configuration
CKEDITOR_5_CUSTOM_CSS = 'path_to.css'  # Optional: Path to custom CSS for CKEditor
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
#CKEDITOR_5_FILE_STORAGE = "path_to_storage.CustomStorage"  # Optional: Custom storage for uploaded files


CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'alignment', '|',  # Alignement du texte
            'fontColor', 'fontBackgroundColor', '|',  # Couleurs de texte et d'arrière-plan
            'fontSize', 'fontFamily', '|',  # Taille et famille de police
            'bulletedList', 'numberedList', '|',
            'blockQuote', 'link', 'imageUpload', '|',
            'undo', 'redo'
        ],
    },
    'extends': {
        'toolbar': [
            'heading', '|',
            'bold', 'italic', 'underline', 'strikethrough', '|',
            'alignment', '|',  # Alignement du texte
            'fontColor', 'fontBackgroundColor', '|',  # Couleurs de texte et d'arrière-plan
            'fontSize', 'fontFamily', '|',  # Taille et famille de police
            'bulletedList', 'numberedList', '|',
            'blockQuote', 'link', 'imageUpload', '|',
            'undo', 'redo', '|',
            'code', 'codeBlock', '|',  # Code et bloc de code
            'insertTable', '|',  # Insertion de tableaux
            'mediaEmbed', '|',  # Intégration de médias (YouTube, etc.)
            'htmlEmbed', '|',  # Intégration de HTML brut
            'sourceEditing', '|',  # Édition du code source
            'highlight', '|',  # Mise en évidence
            'subscript', 'superscript', '|',  # Indice et exposant
            'horizontalLine', '|',  # Ligne horizontale
            'removeFormat', '|',  # Supprimer la mise en forme
            'specialCharacters', '|',  # Caractères spéciaux
            'todoList'  # Liste de tâches
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|',
                'imageStyle:alignLeft', 'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|',
                'toggleImageCaption', '|',
                'resizeImage:original', 'resizeImage:25', 'resizeImage:50', 'resizeImage:75', '|',
                'linkImage'
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn', 'tableRow', 'mergeTableCells',
                'tableProperties', 'tableCellProperties'
            ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'}
            ]
        }
    }
}

# File upload permissions for CKEditor 5
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"  # Options: "staff", "authenticated", "any"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MATERIAL_ADMIN_SITE = {
    'HEADER': 'Portfolio Chadrack Mbu Jess - Connexion Admin',  # Texte de l'en-tête
    'TITLE': 'MBU',  # Titre de l'administration
    'FAVICON': 'images/logo-chadrackmbujess.ico',  # Chemin vers une icône favicon (optionnel)
   # 'MAIN_BG_COLOR': '#3f51b5',  # Couleur de fond principale (optionnel)
    #'MAIN_HOVER_COLOR': '#303f9f',  # Couleur de survol principale (optionnel)
    'PROFILE_PICTURE': 'images/profil1.jpg',  # Photo de profil (optionnel)
    #'PROFILE_BG': 'images/profile-bg.jpg',  # Image de fond du profil (optionnel)
    'LOGIN_LOGO': 'images/logo-chadrackmbujess.png',  # Logo sur la page de connexion (optionnel)
    #'LOGOUT_BG': 'images/logo-chadrackmbujess.png',  # Image de fond sur la page de déconnexion (optionnel)
}


# ------------------------------
# SECURITY
# ------------------------------
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
# X_FRAME_OPTIONS = 'DENY' # Remplacé par la directive CSP 'frame-ancestors'

# ------------------------------
# CONTENT SECURITY POLICY (CSP)
# ------------------------------
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'frame-ancestors': [
            "'self'",
            "https://tousprojetmbujess.pythonanywhere.com/"
        ],
        'default-src': [
            "'self'",
        ],
        'script-src': [
            "'self'",
            "'unsafe-inline'",
            "'unsafe-eval'",  # Requis pour Alpine.js
            "https://cdn.tailwindcss.com",
            "https://unpkg.com",
            "https://cdnjs.cloudflare.com",
            "https://cdn.jsdelivr.net",
        ],
        'style-src': [
            "'self'",
            "'unsafe-inline'",
            "https://cdnjs.cloudflare.com",
            "https://fonts.googleapis.com",
            "https://cdn.jsdelivr.net",
        ],
        'font-src': [
            "'self'",
            "https://cdnjs.cloudflare.com",
            "https://fonts.gstatic.com",
            "https://cdn.jsdelivr.net",
        ],
        'img-src': [
            "'self'",
            "data:",
            "https://ui-avatars.com",
        ],
    }
}

# ------------------------------
# END
# ------------------------------



